ignore:
   - "Pods"
   - "Tests"

coverage:
  status:
    patch:
      default:
        target: 90%
        threshold: 5%
        base: auto 
        if_ci_failed: error
    project:
      default:
        target: 90%
        threshold: 5%
        base: auto
        if_ci_failed: error