# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7.0
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2
  ruby: circleci/ruby@1.2.0

container_medium: &container_medium
  macos:
    xcode: 13.2.1
  resource_class: medium

jobs:
  build-sim:
    <<: *container_medium
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: start_building
    steps:
      - checkout
      - run: mkdir -p deploy-scripts
      - run: echo $CIRCLE_BUILD_NUM
      - run: echo $CIRCLE_PR_NUMBER
      - run:
          name: Build Simulator
          command: fastlane start_building
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > ./../artifact-1;
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > ../artifact-1;            
      - run:
          name: List Folders ../
          command: ls -l ../
      - run:
          name: Print PWD
          command: pwd
      - run:
          name: List Folders
          command: ls -l
      - run:
          name: List Artifacts
          command: ls -l artifacts
      - persist_to_workspace:
            root: .
            paths:
              - artifacts/*
      - persist_to_workspace:
            root: .
            paths:
              - sample/GOT.jpeg
      - persist_to_workspace:
            root: ../
            paths:
              - ../artifact-1
  check_cache:
    <<: *container_medium
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Print PWD
          command: pwd
      - run:
          name: List Folders
          command: ls -l
      - run:
          name: List Folders ../
          command: ls -l ../
      - run:
          name: List Artifacts
          command: ls -l artifacts/*
      - run:
          name: List sample folder
          command: ls -l artifacts/sample
workflows:
  ci-test-workflow:
    jobs:
      - build-sim
      - check_cache:
          requires:
            - build-sim
