# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7.0
  gh: circleci/github-cli@1.0.4
  macos: circleci/macos@2
  ruby: circleci/ruby@1.2.0

container_medium: &container_medium
  macos:
    xcode: 14.1
  resource_class: medium

jobs:
  build-and-test:
    <<: *container_medium
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: build_sim_ci
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Build Simulator
          command: fastlane build_sim_ci
  
workflows:
  version: 2.1
  build-and-release-workflow:
    jobs:
      - build-and-test      
