# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

container_medium: &container_medium
  macos:
    xcode: 13.2.1
  resource_class: medium

jobs:
  build-sim:
    <<: *container_medium
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: start_building
    steps:
      - checkout
      - run:
          name: Build Simulator
          command: fastlane start_building
      - persist_to_workspace:
            root: artifacts
            paths:
              - .

workflows:
  say-hello-workflow:
    jobs:
      - build-sim
