default_platform(:ios)

platform :ios do
  desc "Run tasks when submitting a pull request"
  lane :tasks_for_pull_request do
    scan(
      clean: true,
      scheme: 'CITesting',
      code_coverage: true)
    publish_code_coverage
  end
end