default_platform(:ios)

platform :ios do
  desc "Run tasks when submitting a pull request"
  lane :tasks_for_pull_request do
    scan(
      clean: true,
      scheme: 'CITesting',
      code_coverage: true)
    publish_code_coverage
  end

  lane :start_building do |options|

    xcodebuild(
      archive: true,
      archive_path: "artifacts/CITesting.xcarchive",
      scheme: "CITesting",
      xcargs: "-configuration Debug -sdk 'iphonesimulator' -destination 'generic/platform=iOS Simulator' -derivedDataPath 'artifacts/derivedData'"
    )

    copy_artifacts(
      target_path: "artifacts",
      artifacts: ["./artifacts/CITesting.xcarchive/Products/Applications/CITesting.app","./artifacts/CITesting.xcarchive/dSYMs/CITesting.app.dSYM"]
    )
  end

  lane :build_sim_ci do |options|
      xcversion(version: "~> 14.1.0")
      sh("xcrun simctl list devices")
      fetched_sim = sh("xcrun simctl list | grep 'Fastlane' | cat")
      if !fetched_sim.empty?
          sh("xcrun", "simctl", "delete", "iPhone Fastlane")
      end
      sh("xcrun","simctl","create","iPhone Fastlane", "com.apple.CoreSimulator.SimDeviceType.iPhone-13","com.apple.CoreSimulator.SimRuntime.iOS-15-5")
      scan(
        clean: true,
        output_directory: './artifacts/unit-tests',
        scheme: 'CITesting',
        device: 'iPhone Fastlane',
        code_coverage: true,
        output_types: 'json-compilation-database,html,junit',
        output_files: 'compile_commands.json,report.html,report.junit')
  end
end
