name: Custom Codecov
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -project CITesting.xcodeproj -scheme CITesting -derivedDataPath /Users/runner/Library/Developer/Xcode/DerivedData/CITesting -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -enableCodeCoverage YES clean build test -verbose
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true