name: Custom Codecov
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Text
      run: |
        xcodebuild clean build test -project CITesting.xcodeproj -scheme CITesting -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -enableCodeCoverage YES -verbose
      env:
       destination: ${{ matrix.destination }}
    - name: Update Code Coverage
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)




