name: Custom Codecov
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          mkdir test-reports
          xcodebuild clean build test -project CITesting.xcodeproj -derivedDataPath ${GITHUB_WORKSPACE}/test-reports/ -resultBundlePath Example.xcresult -scheme CITesting -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -enableCodeCoverage YES -verbose | xcpretty --report junit --output ${GITHUB_WORKSPACE}/test-reports/report.xml --report junit --output ${GITHUB_WORKSPACE}/test-reports/report.junit
      - uses: codecov/codecov-action@v2
        with:
            fail_ci_if_error: true
            verbose: true
            directory: ${GITHUB_WORKSPACE}/test-reports/
