name: Custom Codecov
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          xcodebuild clean build test -project CITesting.xcodeproj -derivedDataPath ${GITHUB_WORKSPACE} -resultBundlePath Example.xcresult -scheme CITesting -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' -enableCodeCoverage YES -verbose | xcpretty --report junit --output ${GITHUB_WORKSPACE}/report.xml
      - uses: codecov/codecov-action@v2
        with:
            fail_ci_if_error: true # optional (default = false)
            verbose: true # optional (default = false)