name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: ruby version
      run: ruby -v
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.0'
    - uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'tests'
    - uses: codecov/codecov-action@v2
      with:
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
